# Generated by Django 5.2.11 on 2026-02-24 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'CREATE'), ('update', 'UPDATE'), ('delete', 'DELETE')], help_text='Type of action performed', max_length=10)),
                ('asset_property_number', models.CharField(help_text='Property number (kept even if asset is deleted)', max_length=50)),
                ('description', models.TextField(help_text='Description of the changes made')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When the action was performed')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the user', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Browser user agent')),
                ('asset', models.ForeignKey(help_text='Asset that was modified', null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.asset')),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
