# Generated by Django 5.2.11 on 2026-03-03 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_logs', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'CREATE'), ('update', 'UPDATE'), ('delete', 'DELETE'), ('report', 'REPORT')], help_text='Type of action performed', max_length=10),
        ),
    ]
