# Generated by Django 5.2.11 on 2026-02-24 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_number', models.CharField(help_text='Unique property number for the asset', max_length=50, unique=True)),
                ('asset_type', models.CharField(choices=[('desktop', 'Desktop Computer'), ('laptop', 'Laptop Computer'), ('printer', 'Printer'), ('scanner', 'Scanner'), ('router', 'Router'), ('switch', 'Network Switch'), ('server', 'Server'), ('monitor', 'Monitor'), ('keyboard', 'Keyboard'), ('mouse', 'Mouse'), ('other', 'Other')], help_text='Type of asset', max_length=20)),
                ('brand', models.CharField(help_text='Brand/Manufacturer', max_length=100)),
                ('model', models.CharField(help_text='Model number/name', max_length=100)),
                ('serial_number', models.CharField(blank=True, help_text='Serial number of the asset', max_length=100)),
                ('processor', models.CharField(blank=True, help_text='Processor type (for computers)', max_length=100)),
                ('ram', models.CharField(blank=True, help_text='RAM size (e.g., 8GB DDR4)', max_length=50)),
                ('storage', models.CharField(blank=True, help_text='Storage type and capacity (e.g., 512GB SSD)', max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('under_repair', 'Under Repair'), ('missing', 'Missing'), ('condemned', 'Condemned')], default='active', help_text='Current status of the asset', max_length=20)),
                ('date_acquired', models.DateField(help_text='Date when the asset was acquired')),
                ('warranty_expiration', models.DateField(blank=True, help_text='Warranty expiration date', null=True)),
                ('assigned_personnel', models.CharField(blank=True, help_text='Personnel assigned to this asset', max_length=100)),
                ('remarks', models.TextField(blank=True, help_text='Additional notes or remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(help_text='Branch where the asset is located', on_delete=django.db.models.deletion.CASCADE, to='branches.branch')),
            ],
            options={
                'verbose_name': 'Asset',
                'verbose_name_plural': 'Assets',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['property_number'], name='assets_asse_propert_5c42ac_idx'), models.Index(fields=['branch', 'status'], name='assets_asse_branch__55c94e_idx'), models.Index(fields=['asset_type'], name='assets_asse_asset_t_529092_idx')],
            },
        ),
    ]
