# Generated by Django 5.2.11 on 2026-03-03 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='antivirus_installed',
            field=models.BooleanField(default=False, help_text='Antivirus software installed'),
        ),
        migrations.AddField(
            model_name='asset',
            name='antivirus_last_updated',
            field=models.DateField(blank=True, help_text='Last antivirus definition update date', null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='disk_encrypted',
            field=models.BooleanField(default=False, help_text='Disk encryption is enabled'),
        ),
        migrations.AddField(
            model_name='asset',
            name='firewall_enabled',
            field=models.BooleanField(default=False, help_text='Firewall is enabled'),
        ),
        migrations.AddField(
            model_name='asset',
            name='last_patch_date',
            field=models.DateField(blank=True, help_text='Date of last security patch/update', null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='last_security_scan',
            field=models.DateField(blank=True, help_text='Date of last security scan', null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='os_version',
            field=models.CharField(blank=True, help_text='Operating system version (e.g., Windows 11 Pro, Ubuntu 22.04)', max_length=100),
        ),
    ]
