# Generated by Django 5.2.11 on 2026-03-03 01:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0002_asset_antivirus_installed_and_more'),
        ('branches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(help_text='Domain to block', max_length=255, unique=True)),
                ('reason', models.TextField(help_text='Reason for blocking this domain')),
                ('date_blocked', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('blocked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocked_domains', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Blocked Domain',
                'verbose_name_plural': 'Blocked Domains',
                'ordering': ['-date_blocked'],
                'indexes': [models.Index(fields=['domain'], name='cybersecuri_domain_238342_idx'), models.Index(fields=['is_active'], name='cybersecuri_is_acti_85112e_idx')],
            },
        ),
        migrations.CreateModel(
            name='BlockedIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(help_text='IP address to block', unique=True)),
                ('reason', models.TextField(help_text='Reason for blocking this IP')),
                ('date_blocked', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('blocked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocked_ips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Blocked IP',
                'verbose_name_plural': 'Blocked IPs',
                'ordering': ['-date_blocked'],
                'indexes': [models.Index(fields=['ip_address'], name='cybersecuri_ip_addr_f6d175_idx'), models.Index(fields=['is_active'], name='cybersecuri_is_acti_275615_idx')],
            },
        ),
        migrations.CreateModel(
            name='BranchAgentToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, help_text='Unique token for API authentication', unique=True)),
                ('last_sync', models.DateTimeField(blank=True, help_text='Last time the agent synced with the server', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_token', to='branches.branch')),
            ],
            options={
                'verbose_name': 'Branch Agent Token',
                'verbose_name_plural': 'Branch Agent Tokens',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['token'], name='cybersecuri_token_d87bbb_idx'), models.Index(fields=['is_active'], name='cybersecuri_is_acti_650c9e_idx')],
            },
        ),
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(help_text='IP address from which login was attempted')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=False, help_text='Whether the login attempt was successful')),
                ('user_agent', models.TextField(blank=True, help_text='User agent string from the request')),
                ('username_attempted', models.CharField(blank=True, help_text='Username that was attempted (for failed logins)', max_length=150)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Login Attempt',
                'verbose_name_plural': 'Login Attempts',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['ip_address'], name='cybersecuri_ip_addr_7c75b5_idx'), models.Index(fields=['timestamp'], name='cybersecuri_timesta_53ae41_idx'), models.Index(fields=['success'], name='cybersecuri_success_5dc0f7_idx'), models.Index(fields=['ip_address', 'success'], name='cybersecuri_ip_addr_63d897_idx')],
            },
        ),
        migrations.CreateModel(
            name='SecurityIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_type', models.CharField(choices=[('malware', 'Malware'), ('unauthorized_access', 'Unauthorized Access'), ('data_breach', 'Data Breach'), ('phishing', 'Phishing'), ('hardware_theft', 'Hardware Theft'), ('other', 'Other')], help_text='Type of security incident', max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], help_text='Severity level of the incident', max_length=10)),
                ('description', models.TextField(help_text='Detailed description of the incident')),
                ('date_reported', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('resolution_notes', models.TextField(blank=True, help_text='Notes about how the incident was resolved')),
                ('date_resolved', models.DateTimeField(blank=True, help_text='Date when the incident was resolved', null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_incidents', to='assets.asset')),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_incidents', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_incidents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Security Incident',
                'verbose_name_plural': 'Security Incidents',
                'ordering': ['-date_reported'],
                'indexes': [models.Index(fields=['asset'], name='cybersecuri_asset_i_028417_idx'), models.Index(fields=['incident_type'], name='cybersecuri_inciden_deffe7_idx'), models.Index(fields=['severity'], name='cybersecuri_severit_6728e3_idx'), models.Index(fields=['resolved'], name='cybersecuri_resolve_4477fc_idx'), models.Index(fields=['date_reported'], name='cybersecuri_date_re_69f215_idx')],
            },
        ),
    ]
