# Generated by Django 5.2.11 on 2026-03-03 02:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cybersecurity', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WhitelistedIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(help_text='IP address to whitelist (never blocked)', unique=True)),
                ('reason', models.TextField(help_text='Reason for whitelisting this IP')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whitelisted_ips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Whitelisted IP',
                'verbose_name_plural': 'Whitelisted IPs',
                'ordering': ['-date_added'],
                'indexes': [models.Index(fields=['ip_address'], name='cybersecuri_ip_addr_6a711f_idx'), models.Index(fields=['is_active'], name='cybersecuri_is_acti_ff5ba5_idx')],
            },
        ),
    ]
