# Generated by Django 5.2.11 on 2026-02-24 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Report title', max_length=200)),
                ('report_type', models.CharField(choices=[('monthly', 'Monthly Report'), ('quarterly', 'Quarterly Report'), ('annual', 'Annual Report'), ('custom', 'Custom Report')], help_text='Type of report', max_length=20)),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV')], help_text='Report format', max_length=10)),
                ('file_path', models.CharField(help_text='Path to the generated report file', max_length=500)),
                ('date_from', models.DateField(help_text='Report start date')),
                ('date_to', models.DateField(help_text='Report end date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, help_text='Branch for branch-specific reports (null for provincial)', null=True, on_delete=django.db.models.deletion.CASCADE, to='branches.branch')),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
