# Generated by Django 5.2.11 on 2026-02-24 01:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='generated_by',
            field=models.ForeignKey(help_text='User who generated the report', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['report_type', 'created_at'], name='reports_rep_report__55dc3d_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['branch', 'created_at'], name='reports_rep_branch__59d9c3_idx'),
        ),
    ]
