# Generated by Django 5.2.11 on 2026-02-24 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the municipal branch', max_length=100, unique=True)),
                ('code', models.CharField(help_text='Short code for the branch', max_length=10, unique=True)),
                ('address', models.TextField(help_text='Complete address of the branch')),
                ('contact_number', models.CharField(blank=True, help_text='Branch contact number', max_length=20)),
                ('email', models.EmailField(blank=True, help_text='Branch email address', max_length=254)),
                ('municipality', models.CharField(help_text='Municipality name', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the branch is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Branch',
                'verbose_name_plural': 'Branches',
                'ordering': ['municipality', 'name'],
            },
        ),
    ]
