# Generated by Django 5.2.11 on 2026-02-24 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Assigned branch (not applicable for Super/Provincial Admin)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branch'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('provincial_admin', 'Provincial Admin'), ('main_branch_admin', 'Main Branch Admin'), ('branch_admin', 'Branch Admin'), ('viewer', 'Viewer')], default='viewer', help_text='User role in the system', max_length=20),
        ),
    ]
